### ISSUE TITLE
Old URL on PECL

### ISSUE THREAD

**Issue by TBK** [libvips/php-vips-ext#25]
https://pecl.php.net/package/vips refers to the old repo URL:
```
Homepage | https://github.com/jcupitt/php-vips-ext
```

**Comment by jcupitt** [comment]
I think that'll update when we upload a new release. Perhaps we should make 1.0.10 with fixed links.

**Comment by andypost** [comment]
After new release there's no changes and "Browse Source" also linked to old repo

**Comment by jcupitt** [comment]
I don't see any way to change those links from the https://pecl.php.net admin page. I'll ask on the pecl-dev list.

**Comment by jcupitt** [comment]
OK, fixed now, thanks for reporting this.
