### ISSUE TITLE
Missing 1.0.9 release

### ISSUE THREAD

**Issue by TBK** [libvips/php-vips-ext#26]
The 1.0.9 release is mission here on GH would it be possible to add it?

**Comment by jcupitt** [comment]
Oh, it should be there, what's missing? I see the 1.0.9 tgz file, for example.

**Comment by TBK** [comment]
hmm I can not see it on https://github.com/libvips/php-vips-ext/releases
![image](https://user-images.githubusercontent.com/858296/49789386-28d16500-fd2c-11e8-8891-c88691392bd0.png)

**Comment by TBK** [comment]
Ah I get it now. It is available directly from the master branch.

**Comment by jcupitt** [comment]
Ah OK, yes, I don't think the releases are used much, perhaps they should be disabled.

**Comment by TBK** [comment]
GitHub recently added a new "Watch" option "Release Only - Be notified of new releases, and when participating or @mentioned." which is quite useful to distro package maintainers.

To my knowledge it is triggered by new released getting added to the releases page so it might be worth keeping around.

**Comment by jcupitt** [comment]
OK, that sounds useful. I'll tag 1.0.10 then, that should update the releases page.

**Comment by kdambekalns** [comment]
Also, there is no tag for 1.0.9, which should be there, I think. :)

I missed the 1.0.9 (and 1.0.10) releases, because I would have never checked for the archives in the actual repository. That's what tags, releases and the associated artifacts on GH are actually really useful for.
