### ISSUE TITLE
options for webpsave

### ISSUE THREAD

**Issue by rosell-dk** [libvips/php-vips-ext#27]
Many of the webp options of webpsave are rejected.
I would have assumed that the options for [libvips vips_webpsave](https://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-webpsave) would be working

The following works:
```php
vips_call('webpsave', $im, ['Q' => 80]);
```

But the following does not:
```php
vips_call('webpsave', $im, ['smart_subsample' => true]);
```

It produces the following error (received with vips_error_buffer()):

```webpsave: no property named 'smart_subsample'```

I get the same result when using `vips_image_write_to_file` and when using the *webpsave* method of \Jcupitt\Vips\Image

The following options works with webpsave: `Q`, `lossless`, `strip`
The following options does not work, and produces an error similar to above: `preset`, `near_lossless`, `smart_subsample`, `alpha_q`

I'm on:
vips version: 8.2.2,  vips extension version: 1.0.9, ubuntu 16.04, apache, fpm

**Comment by jcupitt** [comment]
Hello @rosell-dk,

vips 8.2 is pretty old, I would update to 8.7. 8.8 is due soon, which adds yet more `webpsave` options.

**Comment by rosell-dk** [comment]
ah, ok, thanks!
