### ISSUE TITLE
vips_image_write_to_buffer doesn't support options param?

### ISSUE THREAD

**Issue by Necklaces** [libvips/php-vips-ext#28]
Really weird as I can't see any big difference between `vips_image_write_to_buffer` and `vips_image_new_from_file`. Basically I'm trying this:

```
<?php

$image = vips_image_new_from_file('/home/nicsev/dev/images/t3pos7b.jpg', ['access' => 'sequential'])['out'];
vips_image_write_to_file($image, 'out.jpg', ['optimize_coding' => true, 'strip' => true, 'Q' => 10]);

$buf = vips_image_write_to_buffer($image, '.jpg', ['optimize_coding' => true, 'strip' => true, 'Q' => 10]);
var_dump($buf);
```

`vips_image_write_to_file` works fine. At least with .jpg, it doesn't do anything to .png but at least it doesn't crash.

`vips_image_write_to_buffer` on the other hand returns `-1` on both png and jpg, so long as you give it parameters, though it does work if you don't give it any parameters, or if you give it strings only parameters (but then it seems to ignore them).

Am I an idiot? Also, where can I find the documentation/list over options I can give `vips_image_write_to_*` functions?

**Comment by jcupitt** [comment]
Hello, did you find php-vips? It's the more-documented interface to this stuff:

https://libvips.github.io/php-vips/docs/classes/Jcupitt.Vips.Image.html#method_writeToBuffer

The options available depend on the saver that gets called, you have to check the main docs for them. For example, the JPEG buffer saver is documented here:

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave-buffer

**Comment by jcupitt** [comment]
So I would write your example as:

```php
<?php
use Jcupitt\Vips;

$im = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$buf = $im->writeToBuffer('.png');
```

If you use sequential mode, you won't be able to write more than once (ie. you can't write to a file and then write to a buffer). You need to reopen the image:

```php
<?php
use Jcupitt\Vips;

$im = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$im->writeToFile($argv[2]);
$im = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$buf = $im->writeToBuffer('.png');
```

**Comment by Necklaces** [comment]
I did indeed find php-vips, but I was unable to do certain things with it, and I also need speed so I decided to use this instead. 

> If you use sequential mode, you won't be able to write more than once

Right, I didn't know that so that's good to know, but I still get `-1` if I do this:

```
<?php

$buf = vips_image_write_to_buffer($argv[1], '.jpg', ['optimize_coding' => true, 'strip' => true, 'Q' => 10]);
var_dump($buf);
```

**Comment by Necklaces** [comment]
I did indeed find php-vips, but I was unable to do certain things with it, and I also need speed so I decided to use this instead. 

> If you use sequential mode, you won't be able to write more than once

Right, I didn't know that so that's good to know, but I still get `-1` if I do this:

```
<?php

$im = vips_image_new_from_file($argv[1], ['access' => 'sequential']);
$buf = vips_image_write_to_buffer($im, '.jpg', ['optimize_coding' => true, 'strip' => true, 'Q' => 10]);
var_dump($buf);
```

**Comment by kleisauke** [comment]
Could you try this?
```diff
@@ -1,5 +1,5 @@
 <?php
 
-$im = vips_image_new_from_file($argv[1], ['access' => 'sequential']);
+$im = vips_image_new_from_file($argv[1], ['access' => 'sequential'])["out"];
 $buf = vips_image_write_to_buffer($im, '.jpg', ['optimize_coding' => true, 'strip' => true, 'Q' => 10]);
 var_dump($buf);
```

**Comment by Necklaces** [comment]
Whoops
