### ISSUE TITLE
Alpinelinux 029 test fails

### ISSUE THREAD

**Issue by andypost** [libvips/php-vips-ext#33]
Trying to upgrade to latest version I faced with failed test https://github.com/alpinelinux/aports/pull/11938

used to add debug information
```diff
--- 029.phpt.1	2019-11-26 18:06:12.979624226 +0200
+++ 029.phpt	2019-11-26 18:09:12.768886144 +0200
@@ -13,6 +13,7 @@
   $err = vips_call("add", $image, $rg);
   $msg = vips_error_buffer();
 
+var_dump($msg);
   if ($err == -1 &&
     $msg == "add: not one band or 3 bands\n") {
     echo "pass";
```

Not I see there's more then one message
```
$ cat 029.log 

---- EXPECTED OUTPUT
pass
---- ACTUAL OUTPUT
string(106) "vips_realpath: unable to form filename
unix error: No such file or directory
add: not one band or 3 bands
"
---- FAILED
```

Cant fine where `vips_realpath` defined to catch error

**Comment by jcupitt** [comment]
That's curious, it works for me in Ubuntu. I'll try in an Alpine docker image.

**Comment by andypost** [comment]
@jcupitt thank you, please use `alpine:edge` image because it is where I faced with issue and new release (3.1) in progress of build

**Comment by jcupitt** [comment]
Hi again Andy,

It looks like it could be a problem with grsec:

https://www.openwall.com/lists/musl/2015/02/07/2

libvips is trying to canonicalise filenames with `realpath()`, realpath works by opening `/proc/self/fd`, and grsec will block that. This generates an error message which stops 029.php producing the expected output.

As a workaround, I agree, just delete this test. 

Longer term, I've removed realpath from libvips:

https://github.com/libvips/libvips/commit/0bc49a485efd060b09bfd35d6f3da5a676efe894

So the test should start working again in 8.8.4 or later.

Thanks for reporting this!

**Comment by andypost** [comment]
@jcupitt Thank you a lot!

**Comment by andypost** [comment]
I did rebuild with 8.9.2 and now test passes!

Closing it, @jcupitt thanks again)
