### ISSUE TITLE
can't remove metadata  on shared image

### ISSUE THREAD

**Issue by chregu** [libvips/php-vips-ext#34]
I tested my project with libvips 8.9 and get lots of 
`can't remove metadata "orientation" on shared image`
warnings. This seems to be expeced according to https://github.com/libvips/libvips/pull/1483 and https://github.com/lovell/sharp/issues/1986

Is this something, which can be improved in the extension or do I have to copy images before applying metadata changes in my application code?

**Comment by jcupitt** [comment]
Hi @chregu,

Yes, this is a change for 8.9. You must always copy images before modifying metadata. `copy` is very quick (all it does is copy some pointers) so there's no performance implication.

You were always supposed to copy before modify, it just wasn't enforced.

**Comment by jcupitt** [comment]
I've not actually tested php-vips with 8.9 yet, does the test suite pass?

**Comment by chregu** [comment]
Thanks for the response, will adding those copy calls then to my code.

I didn't check the test suite, but my own tests still work, as far as I can tell.
