### ISSUE TITLE
Issues with installation on php 7.2 on Ubuntu Bionic

### ISSUE THREAD

**Issue by jarodium** [libvips/php-vips-ext#40]
Hello @jcupitt 

I was trying the code from #39 but I keep getting this error:

```code
Fatal error: Uncaught Error: Call to undefined function Jcupitt\Vips\vips_type_from_name() in 
/var/www/html/backoffice/vendor/jcupitt/vips/src/Utils.php:95 Stack trace: #0 

/var/www/html/imagem.php(169): 

Jcupitt\Vips\Utils::typeFromName('VipsBlob') #1 
```

I would like to install/upgrade the extension via pecl, but pecl bugs me with that I need vips 8.2 for that.

I have already updated vips, following the gist [here](https://gist.github.com/renexu/366648e488203f0853b8b6bdbaa225d7). This is not the latest version of vips.

Linux box: Ubuntu Bionic ( 18:04 )

My PHP info has this information:

```code
PHP Version: 7.2
Vips headers version | 8.4.5
Vips library version | 8.4.5
Vips ABI version | -1.-1.-1
Major version | 8
Minor version | 4
Micro version | 5
```

vips --version issues this:

```code
vips-8.11.0-Tue Apr 13 10:44:43 UTC 2021
```

composer complains with this ( composer.json entry has ^1.0 has the version required )

```code
Problem 1
    - jcupitt/vips[v1.0.0, ..., v1.0.8] require ext-vips >=0.1.2 -> it is missing from your system. Install or enable PHP's vips extension.
    - Root composer.json requires jcupitt/vips ^1.0 -> satisfiable by jcupitt/vips[v1.0.0, ..., v1.0.8].
This is plenty of evidence that PHP no longer has php-vips-ext installed and enabled.
```

I am intending in following the last comment from @joppuyo ( see issue #36 ) but I would like to make sure if :

1. It works with the version I installed from the gist above.
2. I can install it without libvips-dev ( I fear that installing from the repos may present compat issues, no? )

I have also tried to setup libvips as stated in the docs but to no avail. I could try again, but now following instructions on the github page instead of the website.

On a final note I do wish the distro's repo maintainers add an updated vips to their repos... It's a pain in the neck watching the wonderful things we can do with vips ( and fast ) and not being able to properly update the software...

Best regards and thank you for your patience xD

**Comment by jcupitt** [comment]
Hi @jarodium,

I made you a dockerfile with a sample install for 18.04:

https://github.com/jcupitt/docker-builds/tree/master/php-vips-ubuntu-18.04

**Comment by jarodium** [comment]
Thank you @jcupitt 

I will try it tomorrow at work. I will let you know when I test it.

I'm not that savvy with docker but I would to install it natively in the os.

After the docker installation and test with php and my script, I will try to install libvips and the extension following instructions in github pages. If I can't get it to work, I will to move the box to Ubuntu 20.04 as I think vips is more recent there...

I will close for now this issue, but I will open it again if I encounter more issues. 

Thank you for your help
Best regards

**Comment by jcupitt** [comment]
Don't use docker -- it was just to prove that that sequence of commands will correctly install php and libvips on ubuntu 18.04.

Just copy-paste the commands out of the dockerfile, adjusting as required.

**Comment by jarodium** [comment]
Yes. I made the commands directly in the server. 

The installation works and vipsthumbnail teste.webp --vips-leak --vips-concurrency=1 from the command line. so that particular issue is solved. I will try now to check the metadata code you gave me. I'll let you know the results in that particular issue.

Thank you @jcupitt for your help.
