### ISSUE TITLE
VipsOperation: class "bandand" not found

### ISSUE THREAD

**Issue by futureweb** [libvips/php-vips-ext#48]
Hello,
trying to get "bandand" running with php-vips-ext but it's always failing with "VipsOperation: class "bandand" not found".
Any ideas on that?
thx, bye from Austria
Andreas S.

ps) trying to swap all transparent Pixel in an Image with a defined color like mentioned there: https://github.com/libvips/libvips/issues/872 - but struggling with above Error.

**Comment by jcupitt** [comment]
Hi @futureweb,

Please don't use php-vips-ext directly! It's very low-level, and we don't make any API guarantees. It's only there as a base for higher-level libraries.

You need php-vips:

https://github.com/libvips/php-vips

It defines bandand:

https://libvips.github.io/php-vips/docs/classes/Jcupitt-Vips-Image.html#method_bandand
