### ISSUE TITLE
vips ext cause php fpm crash when curl_exec called on mac m1

### ISSUE THREAD

**Issue by gemini133** [libvips/php-vips-ext#52]
php 7.4.28
tried with vips 8.12.2 from homebrew
tried with compile vips from source (master branch 8.13.0) and re-compile php-vips-ext to make sure headers and library version matched with 8.13.0
and tried with OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

still not working. get 502 error from nginx

get this error from php-fpm only: child 90407 exited on signal 11 (SIGSEGV) after 390.827437 seconds from start

related to #42

**Comment by jcupitt** [comment]
Hello @gemini133,

php-vips 2.0+ does not use the old  php-vips-ext module -- it only needs php-ffi. This is supposed to help with issues like this.

Which php-vips are you using?

**Comment by gemini133** [comment]
thanks for your reply.
Didn't know php vips gets updated with ffi. I'm using vips_cal exposed from php-vips-ext instead of php-vips

**Comment by jcupitt** [comment]
You mustn't use vips-php-ext directly! It's only for use by php-vips.

It's never been supported or documented, we've deprecated it, and we don't plan to maintain it.
