### ISSUE TITLE
Calling `vips_call` Text with an `&` Errors

### ISSUE THREAD

**Issue by panVag** [libvips/php-vips-ext#53]
Hello.

The following calls will return `-1` for no apparent reason:

```php
vips_call('text', null, '&');
vips_call('text', null, 'M&M');
```

Seems like the `&` breaks something.

**Comment by panVag** [comment]
Hi @jcupitt and thanks for your prompt answer. 

I do use php-vips, I just tracked the issue to `vips_call` that's why I though I should open an issue to this repo.

I managed to include ampersands using the HTML entity representation of the character, but it's funny it doesn't work for all HTML entities. For example, `&nbsp;` will still throw an error.

**Comment by jcupitt** [comment]
Ah, OK, that's good.

The main API docs for `vips_text()` have some more information.

https://www.libvips.org/API/current/libvips-create.html#vips-text
